#!/bin/bash

set -eu -o pipefail

case "$1" in
purge|upgrade|failed-upgrade|abort-upgrade)
    ;;

purge|remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    dpkg-divert --package via-deps --remove --rename --divert /usr/bin/via-ui.orig /usr/bin/via-ui
    ;;

*)
    echo "postrm called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac

#DEBHELPER#

exit 0

# vim: ts=4 sts=4 sw=4 et
