#!/bin/bash

set -eu -o pipefail

case "$1" in
install|upgrade)
    dpkg-divert --package via-deps --add --rename --divert /usr/bin/via-ui.orig /usr/bin/via-ui
    ;;

    abort-upgrade)
    ;;

    *)
        echo "preinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0

# vim: ts=4 sts=4 sw=4 et
